name: Build Check

on:
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-check.yml'
      - 'setup.cfg'
      - 'setup.py'
      - 'MANIFEST.in'

  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/build-check.yml'
      - 'setup.cfg'
      - 'setup.py'
      - 'MANIFEST.in'

jobs:
  Build-Check:
    uses: MAK-Relic-Tool/Workflows/.github/workflows/build-check.yml@main
